function out1 = Coriolis_fun_33(in1,in2,in3,in4)
%CORIOLIS_FUN_33
%    OUT1 = CORIOLIS_FUN_33(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-May-2020 18:39:26

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
