function out1 = Coriolis_fun_44(in1,in2,in3,in4)
%CORIOLIS_FUN_44
%    OUT1 = CORIOLIS_FUN_44(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-May-2020 18:40:43

out1 = reshape([1.0./2.0e1,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.0e1,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.0e1,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.0e1,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.0e1,0.0,0.0,0.0,0.0,0.0,0.0,1.0./2.0e1],[6,6]);
