function out1 = N_fun_4(in1,in2)
%N_FUN_4
%    OUT1 = N_FUN_4(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Jul-2020 14:27:20

qd1_4 = in2(7);
qd1_5 = in2(9);
qd1_6 = in2(11);
qd2_1 = in2(2);
qd2_2 = in2(4);
qd2_3 = in2(6);
qd2_4 = in2(8);
qd2_5 = in2(10);
qd2_6 = in2(12);
qt1 = in1(1,:);
qt2 = in1(2,:);
t2 = cos(qd1_4);
t3 = cos(qt1);
t4 = sin(qd1_6);
t5 = cos(qd1_5);
t6 = cos(qd1_6);
t7 = sin(qt1);
t8 = sin(qd1_5);
t9 = sin(qd1_4);
t10 = qd2_3.*1.908953869368798e4;
t11 = qd2_2.*1.908953869368798e4;
out1 = [qd2_1.*pi.*1.05e7,qd2_6.*1.908953869368798e4+t11+cos(qt2).*(t7.*(t8.*t9-t2.*t4.*t5)+t2.*t3.*t6).*(9.81e2./5.0e1)-sin(qt2).*(t3.*t4+t5.*t6.*t7).*(9.81e2./5.0e1),qd2_5.*1.908953869368798e4+t10+t7.*(t2.*t8+t4.*t5.*t9).*(9.81e2./5.0e1)-t3.*t6.*t9.*(9.81e2./5.0e1),qd2_4.*1.104466167277662e4,qd2_5.*1.431715402026599e4+t10,qd2_6.*1.431715402026599e4+t11];
