function out1 = N_fun_3(in1,in2)
%N_FUN_3
%    OUT1 = N_FUN_3(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    20-Jul-2020 14:27:20

qd1_4 = in2(7);
qd1_5 = in2(9);
qd1_6 = in2(11);
qd2_2 = in2(4);
qd2_5 = in2(10);
qd2_6 = in2(12);
qt1 = in1(1,:);
qt2 = in1(2,:);
t2 = cos(qd1_4);
t3 = sin(qt1);
t4 = sin(qd1_4);
t5 = sin(qd1_5);
t6 = t4.*t5;
t7 = cos(qd1_5);
t8 = sin(qd1_6);
t21 = t2.*t7.*t8;
t9 = t6-t21;
t10 = t3.*t9;
t11 = cos(qd1_6);
t12 = cos(qt1);
t13 = t2.*t11.*t12;
t14 = t10+t13;
t15 = cos(qt2);
t16 = sin(qt2);
t17 = t8.*t12;
t18 = t3.*t7.*t11;
t19 = t17+t18;
t20 = sin(qd2_6);
t22 = t14.*t16;
t23 = t15.*t19;
t24 = t22+t23;
t25 = cos(qd2_5);
t26 = cos(qd2_6);
t27 = t14.*t15;
t28 = t27-t16.*t19;
out1 = [t14.*t15.*(-2.20725e1)+t16.*t19.*2.20725e1-t20.*t24.*5.886e1-t24.*(qd2_2-t20.*3.0).*(9.81e2./5.0e1)-t28.*(t25.*t26.*3.0-3.0).*(9.81e2./5.0e1)+t25.*t26.*t28.*5.886e1,0.0,0.0,0.0,0.0,0.0];
