function T = T_fun(in1)
%T_FUN
%    T = T_FUN(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-May-2020 08:29:16

Tt1 = in1(1,:);
Tt2 = in1(2,:);
T = reshape([Tt1,0.0,Tt2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,6]);
